package app.com.server.mapper;

import java.util.List;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;

import app.com.server.dto.CommentDto;
import app.com.server.dto.CreateCommentDto;
import app.com.server.model.Comment;

@Mapper(componentModel = "spring")
public interface CommentMapper {

    @Mapping(target = "userId", source = "user.id")
    @Mapping(target = "userFirstName", source = "user.firstName")
    @Mapping(target = "userLastName", source = "user.lastName")
    @Mapping(target = "username", source = "user.username")
    @Mapping(target = "postId", source = "post.id")
    @Mapping(target = "replyCount", source = "replies", qualifiedByName = "countReplies")
    CommentDto toDto(Comment comment);

    @Mapping(target = "id", ignore = true) // ID is generated by database
    @Mapping(target = "createdAt", ignore = true) // Set by service layer
    @Mapping(target = "updatedAt", ignore = true) // Set by service layer
    @Mapping(target = "user", ignore = true) // Set by service layer
    @Mapping(target = "post", ignore = true) // Set by service layer
    @Mapping(target = "replies", ignore = true) // These are managed by JPA
    Comment toEntity(CreateCommentDto createCommentDto);

    List<CommentDto> toDtoList(List<Comment> comments);

    @Named("countReplies")
    default int countReplies(java.util.Set<app.com.server.model.Reply> replies) {
        return replies != null ? replies.size() : 0;
    }
} 