package app.com.server.mapper;

import java.util.List;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;

import app.com.server.dto.CreatePostDto;
import app.com.server.dto.PostDto;
import app.com.server.model.Post;

@Mapper(componentModel = "spring")
public interface PostMapper {

    @Mapping(target = "userId", source = "user.id")
    @Mapping(target = "userFirstName", source = "user.firstName")
    @Mapping(target = "userLastName", source = "user.lastName")
    @Mapping(target = "username", source = "user.username")
    @Mapping(target = "commentCount", source = "comments", qualifiedByName = "countComments")
    @Mapping(target = "reactionCount", source = "reactions", qualifiedByName = "countReactions")
    PostDto toDto(Post post);

    @Mapping(target = "id", ignore = true) // ID is generated by database
    @Mapping(target = "createdAt", ignore = true) // Set by service layer
    @Mapping(target = "updatedAt", ignore = true) // Set by service layer
    @Mapping(target = "user", ignore = true) // Set by service layer
    @Mapping(target = "comments", ignore = true) // These are managed by JPA
    @Mapping(target = "reactions", ignore = true)
    Post toEntity(CreatePostDto createPostDto);

    List<PostDto> toDtoList(List<Post> posts);

    @Named("countComments")
    default int countComments(java.util.Set<app.com.server.model.Comment> comments) {
        return comments != null ? comments.size() : 0;
    }

    @Named("countReactions")
    default int countReactions(java.util.Set<app.com.server.model.Reaction> reactions) {
        return reactions != null ? reactions.size() : 0;
    }
} 