package app.com.server.mapper;

import java.util.List;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import app.com.server.dto.CreateReactionDto;
import app.com.server.dto.ReactionDto;
import app.com.server.model.Reaction;

@Mapper(componentModel = "spring")
public interface ReactionMapper {

    @Mapping(target = "userId", source = "user.id")
    @Mapping(target = "userFirstName", source = "user.firstName")
    @Mapping(target = "userLastName", source = "user.lastName")
    @Mapping(target = "username", source = "user.username")
    @Mapping(target = "postId", source = "post.id")
    ReactionDto toDto(Reaction reaction);

    @Mapping(target = "id", ignore = true) // ID is generated by database
    @Mapping(target = "user", ignore = true) // Set by service layer
    @Mapping(target = "post", ignore = true) // Set by service layer
    Reaction toEntity(CreateReactionDto createReactionDto);

    List<ReactionDto> toDtoList(List<Reaction> reactions);
} 