package app.com.server.mapper;

import java.util.List;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import app.com.server.dto.CreateReplyDto;
import app.com.server.dto.ReplyDto;
import app.com.server.model.Reply;

@Mapper(componentModel = "spring")
public interface ReplyMapper {

    @Mapping(target = "userId", source = "user.id")
    @Mapping(target = "userFirstName", source = "user.firstName")
    @Mapping(target = "userLastName", source = "user.lastName")
    @Mapping(target = "username", source = "user.username")
    @Mapping(target = "commentId", source = "comment.id")
    ReplyDto toDto(Reply reply);

    @Mapping(target = "id", ignore = true) // ID is generated by database
    @Mapping(target = "createdAt", ignore = true) // Set by service layer
    @Mapping(target = "updatedAt", ignore = true) // Set by service layer
    @Mapping(target = "user", ignore = true) // Set by service layer
    @Mapping(target = "comment", ignore = true) // Set by service layer
    Reply toEntity(CreateReplyDto createReplyDto);

    List<ReplyDto> toDtoList(List<Reply> replies);
} 