package app.com.server.mapper;

import app.com.server.dto.CreateUserDto;
import app.com.server.dto.UserDto;
import app.com.server.model.User;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;

import java.util.List;

@Mapper(componentModel = "spring")
public interface UserMapper {

    @Mapping(target = "postCount", source = "posts", qualifiedByName = "countPosts")
    @Mapping(target = "commentCount", source = "comments", qualifiedByName = "countComments")
    UserDto toDto(User user);

    @Mapping(target = "id", ignore = true) // ID is generated by database
    @Mapping(target = "posts", ignore = true) // These are managed by JPA
    @Mapping(target = "comments", ignore = true)
    @Mapping(target = "replies", ignore = true)
    @Mapping(target = "reactions", ignore = true)
    User toEntity(CreateUserDto createUserDto);

    List<UserDto> toDtoList(List<User> users);

    @Named("countPosts")
    default int countPosts(java.util.Set<app.com.server.model.Post> posts) {
        return posts != null ? posts.size() : 0;
    }

    @Named("countComments")
    default int countComments(java.util.Set<app.com.server.model.Comment> comments) {
        return comments != null ? comments.size() : 0;
    }
} 